services:
  pharmacies.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=3000
    container_name: pharmacies.api
    image: pharmacies.api
    build:
      context: .
      dockerfile: Pharmacies/Dockerfile
    ports:
      - "5088:3000"
    depends_on:
      database.server:
        condition: service_healthy

  database.server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database.server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123

    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "Password123", "-Q", "SELECT 1", "-b", "-C" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s

  pharmacies.client:
    build:
      context: pharmacies-app
      dockerfile: Dockerfile
    image: pharmacies.client
    container_name: "pharmacies.client"
    ports:
      - "5000:5000"
    depends_on:
      - pharmacies.api